[build]
  base = "onebox"
  command = """
    cd backend && npm install && npm run build && \
    cd ../frontend && npm install && \
    npm run build
  """
  publish = "frontend/dist"
  functions = "backend/src"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "body-parser", "cors", "dotenv", "@elastic/elasticsearch", "imapflow", "winston"]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true