[build]
  base = "onebox/"
  publish = "frontend/dist"
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"

[functions]
  directory = "backend/src"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  GEMINI_API_KEY = ""
  SLACK_WEBHOOK_URL = ""
  WEBHOOK_URL = ""